version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "35432:5432"
    environment:
       POSTGRES_PASSWORD: postgres
  test-db:
    image: postgres
    restart: always
    ports:
      - "35433:5432" # 👈 Note the 5433 port (since we are using 5432 for our regular db)
    environment:
      POSTGRES_PASSWORD: pass123
